version: '3.8'

services:
  camunda:
    image: camunda/camunda-bpm-platform:run-7.20.0
    container_name: camunda-bpm-run-test
    ports:
      - "8080:8080"
    environment:
      - "TZ=Europe/Moscow"
    volumes:
      - camunda_test_data:/camunda/internal/data
      - ./my-default.yml:/camunda/configuration/default.yml
volumes:
  camunda_test_data: